#!/usr/bin/env node

const prog = require('caporal');

function check(num){
    let k = true;
    num = num / 2;
    for(var i = 2; i <= num; ++i){
	if (num % i == 0) k = false;
    }
    
    if (k == true && num > 1)console.log('Day la so nguyen to!')
    else console.log('Day khong phai la so nguyen to!');
}

prog
    .argument('number','number', prog.INT)
    .action((args, options, logger) =>{
        check(args.number); //Du :v vay luon ha :vi
    });

prog.parse(process.argv);
